[build]
  base    = "new-smile-guide"
  command = "npm install && npm run build" # Explicitly run npm install in the base directory
  publish = "build" # This is relative to the 'base' directory

[build.environment]
  NODE_VERSION = "18"
  CI = "false" # Prevent warnings from being treated as errors
